export const buttonSnippets = [
  {
    id: 5,
    title: 'Wipe Left',
    category: 'button',
    type: 'wipe-left',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 6,
    category: 'button',
    title: 'Fill Center',
    type: 'fill-center',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 7,
    category: 'button',
    title: 'Diagonal Wipe',
    type: 'diagonal-wipe',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
   {
    id: 8,
    category: 'button',
    title: 'Circular Fill',
    type: 'circular-fill',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 9,
    category: 'button',
    title: 'Double Wipe',
    type: 'double-wipe',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 10,
    category: 'button',
    title: 'Border Sweep',
    type: 'border-sweep',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  }
]