export const buttonSnippets = [
  {
    id: 5,
    title: 'Wipe Left',
    category: 'button',
    type: 'wipe-left',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 6,
    category: 'button',
    title: 'Fill Center',
    type: 'fill-center',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 7,
    category: 'button',
    title: 'Diagonal Wipe',
    type: 'diagonal-wipe',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 8,
    category: 'button',
    title: 'Circular Fill',
    type: 'circular-fill',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 9,
    category: 'button',
    title: 'Double Wipe',
    type: 'double-wipe',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 10,
    category: 'button',
    title: 'Border Sweep',
    type: 'border-sweep',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 11,
    category: 'button',
    title: 'Shifting Border',
    type: 'shifting-border',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 12,
    category: 'button',
    title: 'Push Down',
    type: 'push-down',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 13,
    category: 'button',
    title: 'Neon Flux',
    type: 'neon-flux',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 14,
    category: 'button',
    title: 'Super Wave',
    type: 'super-wave',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 15,
    category: 'button',
    title: 'Starlight',
    type: 'star-light',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 16,
    category: 'button',
    title: 'Plasma Flip',
    type: 'plasma-flip',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 17,
    category: 'button',
    title: 'Crystal Pop',
    type: 'crystal-pop',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 18,
    category: 'button',
    title: 'Frost Shake',
    type: 'frost-shake',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 19,
    category: 'button',
    title: 'Text Quake',
    type: 'text-quake',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 20,
    category: 'button',
    title: 'Tear Apart',
    type: 'tear-apart',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 21,
    category: 'button',
    title: 'Radar Sweep',
    type: 'radar-sweep',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 22,
    category: 'button',
    title: 'Old Keyboard Style',
    type: 'old-keyboard-style-button',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 23,
    category: 'button',
    title: 'Origami Fold',
    type: 'origami-fold',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 24,
    category: 'button',
    title: 'Snake-style Retro',
    type: 'snake-style-retro',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 25,
    category: 'button',
    title: 'Space Warp',
    type: 'space-warp',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 26,
    category: 'button',
    title: 'Liquid Fill',
    type: 'liquid-fill',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 27,
    category: 'button',
    title: 'Gummy Drop',
    type: 'gummy-drop',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 28,
    category: 'button',
    title: 'Exploding Particles',
    type: 'exploding-particles',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 29,
    category: 'button',
    title: 'Layer Slice',
    type: 'layer-slice',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
  {
    id: 30,
    category: 'button',
    title: 'Pixelated Art',
    type: 'pixelated-art',
    html: `<div class="flex items-center space-x-4"><button id="decrement" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">-</button><span id="count" class="text-xl font-bold">0</span><button id="increment" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">+</button></div>`,
    css: `/* CSS is handled by Tailwind */`,
    js: `const decrementButton = document.getElementById('decrement'); /* ... */`,
  },
]